name: file_android
description: Este é um plugin para salvar arquivo nas pastas de mídias do android
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.file_android
        pluginClass: FileAndroidPlugin
